#!/usr/bin/env bash
#
#date:2019.10.15 11:50
#usage :monitor website

urllist=$(egrep "com|cn" ./url.txt)
for url in ${urllist}; do
	statuCode=$(curl -I --connect-timeout 3 -m 10 -s ${url} | grep "HTTP")
	if [[ ${statuCode: 9: 3} -eq 200 ]] || [[ ${statuCode: 9: 3} -eq 302 ]];then
	    echo "$(date +'%Y-%m-%d %H:%M:%S') -run monitor program ${url} is ok">>/var/log/urlMoniyor.log
	else
	    echo "$(date +'%Y-%m-%d %H:%M:%S') -run monitor program ${url} is failed">>/var/log/urlMointor.log
	    echo "[ERROR] ${url} Downtime! Please repair." | mail -s "warnning website" 1044207773@qq.com
	fi
done
